apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard-pvc.yaml
  - bazarr-pvc.yaml
  - bookshelf-pvc.yaml
  - nextcloud-pvc.yaml
  - plex-pvc.yaml
  - prowlarr-pvc.yaml
  - qbittorrent-pvc.yaml
  - radarr-pvc.yaml
  - sonarr-pvc.yaml
