apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard
  - bazarr
  - bookshelf
  - flaresolverr
  - nextcloud
  - plex
  - prowlarr
  - qbittorrent
  - radarr
  - sonarr
