apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard
  - bazarr
  - flaresolverr
  - immich
  - nextcloud
  - plex
  - prowlarr
  - qbittorrent
  - radarr
  - readarr
  - sonarr
