apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard-namespace.yaml
  - flaresolverr-namespace.yaml
  - nextcloud-namespace.yaml
  - plex-namespace.yaml
  - prowlarr-namespace.yaml
  - qbittorrent-namespace.yaml
  - sonarr-namespace.yaml
