apiVersion: v1
kind: Service
metadata:
  name: bookshelf
  namespace: bookshelf
spec:
  selector:
    app: bookshelf
  ports:
    - name: http
      protocol: TCP
      port: 8787
      targetPort: 8787
