apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - nextcloud-readonly-pv.yaml
